/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vinny Passmore (https://sketchfab.com/HPrendering)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eye-blend-a8259f43d41e4204a7e9746dfd112c30
Title: Eye Blend
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/models/eye_blend.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Iris_Iris_001_Material_0.geometry}
        material={materials.Iris_001_Material}
        position={[0, 0, -2.824]}
        scale={123.881}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sclera_Sclera_001_Material_0.geometry}
        material={materials.Sclera_001_Material}
        scale={120.464}
      />
    </group>
  )
}

useGLTF.preload('/assets/models/eye_blend.glb')